### ISSUE TITLE
[MAINT] Reorganize the 'Core' module.

### ISSUE THREAD

**Issue by oddkiva** [DO-CV/sara#105]
This issue has arisen from PR #102.

Break down the header files in the 'Core' module into smaller header files. The header files are quite monolithic as most of the time, many template classes are defined in a header file.

For example, break down the following header files:
- [x] `UseDOCore.cmake`: simplify the implementation, cf PR #102.
- [x] `Image.hpp`: WIP cf. PR #109
- [x] `MultiArray.hpp`: cf. PR #107
- [x] ArrayIterators.hpp: cf. PR #111
