### ISSUE TITLE
[MAINT] Add and clean unit tests for `ImageProcessing`.

### ISSUE THREAD

**Issue by oddkiva** [DO-CV/sara#127]
Tests are needed for:
- [x] Deriche: cf. PR #123
- [x] Determinant: ~~WIP~~ cf. PR #130 
- [x] Differential: cf. PR #129
- [x] Gaussian pyramid: cf. PR #145 but better unit tests are needed.
- [x] Extremum localization: cf PR #131.
- [x] ImagePyramid: cf. PR #133
- [x] Interpolation: cf. PR #123
- [x] Linear Filtering: ~~WIP~~ cf. PR #124
- [x] Local extrema: cf. PR #131
- [x] Norm: cf. PR #135
- [x] Orientation cf. PR #136 
- [x] Scaling: cf PR #144
- [x] Second moment matrix: cf. PR #137
- [x] Warp: cf PR. #146
